### PR TITLE
Test update to 1.9.4

### PR DESCRIPTION
**Pull request by BondarenkoArtur**

### CODE REVIEW

**Comment by AoKMiKeY** [comment]
@BondarenkoArtur How well does this run on 1.9.4?

**Comment by BondarenkoArtur** [comment]
Looks like there is some problems with custom blocks gui

**Comment by AoKMiKeY** [comment]
@BondarenkoArtur Do you think you can get these issues fixed? If so then I will wait to pull. If not then I can pull now and I will see about fixing them myself. The update looks good by the way. I couldn't get my head around the different rendering system.

**Comment by BondarenkoArtur** [comment]
I don't have a lot of free time. I can't promise.
Also there is a need to fix colors in overlay...

**Comment by AoKMiKeY** [comment]
@BondarenkoArtur I haven't been able to take much of a look yet. I will pull in the changes soon :) I'm going to have a look first.

**Pull request merged**
